word_list = [
    'abruptly', 'absurd', 'abyss', 'affix', 'askew', 'avenue', 'awkward',
    'axiom', 'azure', 'bagpipes', 'bandwagon', 'banjo', 'bayou', 'beekeeper',
    'bikini', 'blitz', 'blizzard', 'boggle', 'bookworm', 'boxcar', 'buffalo',
    'buzzard', 'buzzing', 'cobweb', 'croquet', 'crypt', 'cycle', 'daiquiri',
    'dizzying', 'duplex', 'dwarves', 'embezzle', 'equip', 'espionage',
    'exodus', 'fjord', 'flapjack', 'foxglove', 'frazzled', 'fuchsia',
    'galaxy', 'galvanize', 'gazebo', 'gizmo', 'glowworm', 'glyph', 'gnarly',
    'gossip', 'haiku', 'haphazard', 'hyphen', 'icebox', 'injury', 'ivory',
    'jackpot', 'jaundice', 'jawbreaker', 'jazzy', 'jelly', 'jigsaw', 'jinx',
    'jockey', 'jogging', 'jovial', 'joyful', 'juicy', 'jukebox', 'jumbo',
    'kayak', 'kazoo', 'keyhole', 'khaki', 'kiosk', 'klutz', 'knapsack',
    'larynx', 'lucky', 'luxury', 'lymph', 'matrix', 'microwave', 'mnemonic',
    'mystify', 'nightclub', 'nowadays', 'nymph', 'onyx', 'oxygen', 'pajama',
    'pixel', 'pneumonia', 'polka', 'psyche', 'puppy', 'puzzling', 'quartz',
    'queue', 'quiz', 'quorum', 'rhubarb', 'rhythm', 'rickshaw', 'scratch',
    'sphinx', 'spritz', 'squawk', 'strength', 'subway', 'syndrome',
    'topaz', 'transcript', 'twelfth', 'unknown', 'unzip', 'vaporize',
    'vixen', 'vodka', 'voodoo', 'vortex', 'waltz', 'whiskey', 'wizard',
    'wristwatch', 'xylophone', 'youthful', 'zigzag', 'zombie',
]
